import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'



export default function Home() {
  return (
    <div className=''>
      <Head>
        <title className='hoverEffect'>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen max-w-7xl px-8'>
          {/* sidebar */}
            
          <Sidebar/>

          {/* fide */}


          {/* widget */}


          {/* modal */}
      </main>
      

     
    </div>
  )
}
