import Head from 'next/head'
import Feedes from '../components/Feedes'
import Sidebar from '../components/Sidebar'
import Wedget from '../components/Wedget'



export default function Home({newResult}) {
  return (
    <div className=''>
      <Head>
        <title className='hoverEffect'>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen px-8'>
          {/* sidebar */}
            
          <Sidebar/>

          {/* feede */}
            <Feedes/>
          
          {/* widget */}

            <Wedget newResult={newResult.articles}/>
          {/* modal */}

      </main>
      

     
    </div>
  )
}


export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://saurav.tech/NewsAPI/top-headlines/category/business/us.json`)
  const newResult = await res.json()

  // Pass data to the page via props
  return { props: { newResult } }
}